In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('../data/processed/02_cleaning.csv')

print(df)

     Serial_No                   Name   Type_1  Type_2  Total  HP  Attack  \
0            1              Bulbasaur    Grass  Poison    318  45      49
1            2                Ivysaur    Grass  Poison    405  60      62
2            3               Venusaur    Grass  Poison    525  80      82
3            3  VenusaurMega Venusaur    Grass  Poison    625  80     100
4            4             Charmander     Fire     NaN    309  39      52
..         ...                    ...      ...     ...    ...  ..     ...
795        719                Diancie     Rock   Fairy    600  50     100
796        719    DiancieMega Diancie     Rock   Fairy    700  50     160
797        720    HoopaHoopa Confined  Psychic   Ghost    600  80     110
798        720     HoopaHoopa Unbound  Psychic    Dark    680  80     160
799        721              Volcanion     Fire   Water    600  80     110

     Defense  Sp_Atk  Sp_Def  Speed  Generation  Legendary
0         49      65      65     45           1      False
1         63      80      80     60           1      False
2         83     100     100     80           1      False
3        123     122     120     80           1      False
4         43      60      50     65           1      False
..       ...     ...     ...    ...         ...        ...
795      150     100     150     50           6       True
796      110     160     110    110           6       True
797       60     150     130     70           6       True
798       60     170     130     80           6       True
799      120     130      90     70           6       True

[800 rows x 13 columns]

In [6]:
df['Offensive_Power'] = df['Attack'] + df['Sp_Atk']

df[["Name", "Attack", "Sp_Atk", "Offensive_Power"]].head()

                    Name  Attack  Sp_Atk  Offensive_Power
0              Bulbasaur      49      65              114
1                Ivysaur      62      80              142
2               Venusaur      82     100              182
3  VenusaurMega Venusaur     100     122              222
4             Charmander      52      60              112

In [7]:
df["Defensive_Power"] = df["Defense"] + df["Sp_Def"]

df[["Name", "Defense", "Sp_Def", "Defensive_Power"]].head()

                    Name  Defense  Sp_Def  Defensive_Power
0              Bulbasaur       49      65              114
1                Ivysaur       63      80              143
2               Venusaur       83     100              183
3  VenusaurMega Venusaur      123     120              243
4             Charmander       43      50               93

In [8]:
df["Power_Diff"] = df["Offensive_Power"] - df["Defensive_Power"]

df[["Name", "Offensive_Power", "Defensive_Power", "Power_Diff"]].head()

                    Name  Offensive_Power  Defensive_Power  Power_Diff
0              Bulbasaur              114              114           0
1                Ivysaur              142              143          -1
2               Venusaur              182              183          -1
3  VenusaurMega Venusaur              222              243         -21
4             Charmander              112               93          19

💡 How to read it

- Power_Diff > 0 → offensive Pokémon
- Power_Diff < 0 → defensive Pokémon
- Power_Diff ≈ 0 → balanced Pokémon

In [9]:
def classify_role(row):
    if row["Power_Diff"] > 20:
        return "Attacker"
    elif row["Power_Diff"] < -20:
        return "Defender"
    else:
        return "Balanced"

df["Role"] = df.apply(classify_role, axis=1)

df[["Name", "Offensive_Power", "Defensive_Power", "Role"]].head()

                    Name  Offensive_Power  Defensive_Power      Role
0              Bulbasaur              114              114  Balanced
1                Ivysaur              142              143  Balanced
2               Venusaur              182              183  Balanced
3  VenusaurMega Venusaur              222              243  Defender
4             Charmander              112               93  Balanced

In [10]:
df['Role'].value_counts()

Role
Balanced    340
Attacker    269
Defender    191
Name: count, dtype: int64

In [11]:
print(df)

     Serial_No                   Name   Type_1  Type_2  Total  HP  Attack  \
0            1              Bulbasaur    Grass  Poison    318  45      49
1            2                Ivysaur    Grass  Poison    405  60      62
2            3               Venusaur    Grass  Poison    525  80      82
3            3  VenusaurMega Venusaur    Grass  Poison    625  80     100
4            4             Charmander     Fire     NaN    309  39      52
..         ...                    ...      ...     ...    ...  ..     ...
795        719                Diancie     Rock   Fairy    600  50     100
796        719    DiancieMega Diancie     Rock   Fairy    700  50     160
797        720    HoopaHoopa Confined  Psychic   Ghost    600  80     110
798        720     HoopaHoopa Unbound  Psychic    Dark    680  80     160
799        721              Volcanion     Fire   Water    600  80     110

     Defense  Sp_Atk  Sp_Def  Speed  Generation  Legendary  Offensive_Power  \
0         49      65      65     45           1      False              114
1         63      80      80     60           1      False              142
2         83     100     100     80           1      False              182
3        123     122     120     80           1      False              222
4         43      60      50     65           1      False              112
..       ...     ...     ...    ...         ...        ...              ...
795      150     100     150     50           6       True              200
796      110     160     110    110           6       True              320
797       60     150     130     70           6       True              260
798       60     170     130     80           6       True              330
799      120     130      90     70           6       True              240

     Defensive_Power  Power_Diff      Role
0                114           0  Balanced
1                143          -1  Balanced
2                183          -1  Balanced
3                243         -21  Defender
4                 93          19  Balanced
..               ...         ...       ...
795              300        -100  Defender
796              220         100  Attacker
797              190          70  Attacker
798              190         140  Attacker
799              210          30  Attacker

[800 rows x 17 columns]

In [12]:
df.to_csv('../data/processed/Feature_enginnered.csv', index = False)